# Generated by Django 3.2.4 on 2021-06-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210614_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='name_product',
            field=models.CharField(max_length=200, verbose_name='Nombre del producto'),
        ),
    ]
