# Generated by Django 3.2.4 on 2021-06-12 22:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210611_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Un usuario con ese email ya existe.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, help_text='Ayude a distinguir fácilmente a los usuarios y a realizar consultas.Los clientes son el principal tipo de usuario.', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Establézcalo en verdadero cuando el usuario haya verificado su dirección de correo electrónico.', verbose_name='verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(code='Inválido', message='El número de teléfono debe ingresarse en el formato: +999999999. Se permiten hasta 15 dígitos.', regex='\\+?1?\\d{9,15}$')]),
        ),
    ]
