# Generated by Django 3.2.4 on 2021-06-12 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha última de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Esta activo')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('code', models.CharField(max_length=20, verbose_name='Codigo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Precio')),
                ('iva', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='IVA')),
                ('price_total', models.DecimalField(decimal_places=5, max_digits=9, verbose_name='Precion + IVA')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_product_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_product_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Última modificación por')),
            ],
            options={
                'permissions': (('retrieve_product', 'Can retrieve product data'), ('list_product', 'Can list product data')),
            },
        ),
        migrations.CreateModel(
            name='ProductLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='Campo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('deleted', models.BooleanField(default=False, verbose_name='Eliminar')),
                ('before_char', models.CharField(blank=True, max_length=500, null=True, verbose_name='Texto antes')),
                ('after_char', models.CharField(blank=True, max_length=500, null=True, verbose_name='Texto después')),
                ('before_text', models.TextField(blank=True, null=True, verbose_name='Texto largo antes')),
                ('after_text', models.TextField(blank=True, null=True, verbose_name='Texto largo después')),
                ('before_id', models.IntegerField(blank=True, null=True, verbose_name='Id antes')),
                ('after_id', models.IntegerField(blank=True, null=True, verbose_name='Id después')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_productlog_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Registro')),
            ],
            options={
                'permissions': (('retrieve_productlog', 'Can retrieve Productlog data'), ('list_productlog', 'Can list Productlog data')),
            },
        ),
    ]
