# Generated by Django 3.2.4 on 2021-06-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('DISPONIBLE', 'DISPONIBLE'), ('AGOTADO', 'AGOTADO')], max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor'),
        ),
    ]
