PENDIENTE = 'PENDIENTE'
ABONADO = 'ABONADO'
PAGADO = 'PAGADO'
PAGADO_ENVIADO = 'PAGADO - ENVIADO'
PAGADO_ENTREGADO = 'PAGADO - ENTREGADO'
CANCELADO = 'CANCELADO'
FINALIZADO = 'FINALIZADO'

STATUS = [
    (PENDIENTE, PENDIENTE),
    (ABONADO, ABONADO),
    (PAGADO, PAGADO),
    (PAGADO_ENVIADO, PAGADO_ENVIADO),
    (PAGADO_ENTREGADO, PAGADO_ENTREGADO),
    (CANCELADO, CANCELADO),
    (FINALIZADO, FINALIZADO),
]